#!/bin/sh

# fill in a large random string which matches ropend's
ROPEN_SECRET=''

# replace this with your own if you want
ROPEN_URL='http://tlrobinson.net/ropen/ropen.php'

# uncomment and fill in this if the default user/host detection doesn't work
#SSH_CONNECT_STRING='user@host'


urlencode() {
	# http://www.shelldorado.com/scripts/cmds/urlencode
	EncodeEOL=yes
	awk '
	    BEGIN {
		# We assume an awk implementation that is just plain dumb.
		# We will convert an character to its ASCII value with the
		# table ord[], and produce two-digit hexadecimal output
		# without the printf("%02X") feature.

		EOL = "%0A"		# "end of line" string (encoded)
		split ("1 2 3 4 5 6 7 8 9 A B C D E F", hextab, " ")
		hextab [0] = 0
		for ( i=1; i<=255; ++i ) ord [ sprintf ("%c", i) "" ] = i + 0
		if ("'"$EncodeEOL"'" == "yes") EncodeEOL = 1; else EncodeEOL = 0
	    }
	    {
		encoded = ""
		for ( i=1; i<=length ($0); ++i ) {
		    c = substr ($0, i, 1)
		    if ( c ~ /[a-zA-Z0-9.-]/ ) {
			encoded = encoded c		# safe character
		    } else if ( c == " " ) {
			encoded = encoded "+"	# special handling
		    } else {
			# unsafe character, encode it as a two-digit hex-number
			lo = ord [c] % 16
			hi = int (ord [c] / 16);
			encoded = encoded "%" hextab [hi] hextab [lo]
		    }
		}
		if ( EncodeEOL ) {
		    printf ("%s", encoded EOL)
		} else {
		    print encoded
		}
	    }
	    END {
	    	#if ( EncodeEOL ) print ""
	    }
	' "$@"
}

# attempt to figure out the username and host of the current machine (assume you SSH'd in) 
if [ ! "$SSH_CONNECT_STRING" ]; then
	SSH_CONNECT_STRING="$USER@$(echo $SSH_CONNECTION | cut -d ' ' -f 3)"
fi

PATHS=''
APP='-'

while [ "$#" -gt "0" ]
do
	case $1 in
		-s)
			shift
			ROPEN_SECRET=$1
			;;
		-a)
			shift
			APP=$1
			;;
		*)	
			TMP_PATH=$(cd -P -- "$(dirname -- "$1")" && pwd -P) && TMP_PATH=$TMP_PATH/$(basename -- "$1")
			PATHS="$PATHS $TMP_PATH"
			;;
	esac
	shift
done

if [ ! "$ROPEN_SECRET" ]; then
	echo "Please fill in \$ROPEN_SECRET in $0 with a random string or use the -s argument"
	exit 1
fi

SSH_CONNECT_STRING=`echo $SSH_CONNECT_STRING | urlencode`
APP=`echo $APP | urlencode`
PATHS=`echo $PATHS | urlencode`

curl -b "ropen=$ROPEN_SECRET" "$ROPEN_URL?mode=put&connect=$SSH_CONNECT_STRING&app=$APP&paths=$PATHS"
